class ExcelFunctionError(Exception): ...

class TokenizerError(Exception):...

class ParseError(Exception): ...

class CoercionError(Exception): ...

class SheetNotFound(Exception): ...

class NameNotFound(Exception): ...

class InvalidOperation(Exception): ...

class CycleError(Exception): ...